accounts/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login',views.login,name='login'),
    url(r'^logout',views.logout, name='logout'),
    url(r'^register',views.register,name='register'),	
)

yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

yunjz_prj/accounts/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login',views.login,name='login'),
    url(r'^logout',views.logout, name='logout'),
    url(r'^register',views.register,name='register'),	
)

yunjz_prj/yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/',include('jizhang.urls',namespace='jizhang')),
]

accounts/models.py
from django.db import models

# Create your models here.

yunjz_prj/accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
#coding=utf-8
from django import forms
from django.contrib.auth.models import User

# Register your models here.
ALLOW_CHAR = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

class RegisterForm(forms.Form):
    username=forms.CharField(label=u"昵称",max_length=40,
            widget=forms.TextInput(attrs={'size': 40,'class':"form-control"}))
    email=forms.EmailField(label=u"邮件",max_length=40,
            widget=forms.EmailInput(attrs={'size': 40,'class':"form-control"}))    
    password=forms.CharField(label=u"密码",max_length=20,
            widget=forms.PasswordInput(attrs={'size': 20,'class':"form-control"}))
    re_password=forms.CharField(label=u"重复密码",max_length=20,
            widget=forms.PasswordInput(attrs={'size': 20,'class':"form-control"}))

    def clean_username(self):
        '''验证昵称'''
        if len(self.cleaned_data["username"])<4:
            raise forms.ValidationError(u"昵称长度不能小于4")
        else:    
            for a in self.cleaned_data["username"]:
                if a not in ALLOW_CHAR:
                    raise forms.ValidationError(u"昵称仅能用字母或数字")
            
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        else:
            raise forms.ValidationError(u"该昵称已经被使用请使用其他的昵称")
        
    def clean_email(self):
        '''验证重复email'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError(u"该邮箱已经被使用请使用其他的邮箱")

    def clean_password(self):
        if len(self.cleaned_data["password"])<6:
            raise forms.ValidationError(u"密码长度不能小于6")
        else:    
            for a in self.cleaned_data["password"]:
                if a not in ALLOW_CHAR:
                    raise forms.ValidationError(u"密码仅能用字母或数字")    
        return self.cleaned_data["password"]
        
    def clean(self):
        """验证其他非法"""
        cleaned_data = super(RegisterForm, self).clean()

        if cleaned_data.get("password") == cleaned_data.get("username"):
            raise forms.ValidationError(u"用户名和密码不能一样")
        if cleaned_data.get("password") != cleaned_data.get("re_password"):
            raise forms.ValidationError(u"两次输入密码不一致")

        return cleaned_data

    def save(self):
        username=self.cleaned_data["username"]
        email=self.cleaned_data["email"]
        password=self.cleaned_data["password"]
        user=User.objects.create_user(username,email,password)
        return user

yunjz_prj/accounts/forms.py
#coding=utf-8
from django import forms
from django.contrib.auth.models import User

# Register your models here.
ALLOW_CHAR = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

class RegisterForm(forms.Form):
    username=forms.CharField(label=u"昵称",max_length=40,
            widget=forms.TextInput(attrs={'size': 40,'class':"form-control"}))
    email=forms.EmailField(label=u"邮件",max_length=40,
            widget=forms.EmailInput(attrs={'size': 40,'class':"form-control"}))    
    password=forms.CharField(label=u"密码",max_length=20,
            widget=forms.PasswordInput(attrs={'size': 20,'class':"form-control"}))
    re_password=forms.CharField(label=u"重复密码",max_length=20,
            widget=forms.PasswordInput(attrs={'size': 20,'class':"form-control"}))

    def clean_username(self):
        '''验证昵称'''
        if len(self.cleaned_data["username"])<4:
            raise forms.ValidationError(u"昵称长度不能小于4")
        else:    
            for a in self.cleaned_data["username"]:
                if a not in ALLOW_CHAR:
                    raise forms.ValidationError(u"昵称仅能用字母或数字")
            
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        else:
            raise forms.ValidationError(u"该昵称已经被使用请使用其他的昵称")
        
    def clean_email(self):
        '''验证重复email'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError(u"该邮箱已经被使用请使用其他的邮箱")

    def clean_password(self):
        if len(self.cleaned_data["password"])<6:
            raise forms.ValidationError(u"密码长度不能小于6")
        else:    
            for a in self.cleaned_data["password"]:
                if a not in ALLOW_CHAR:
                    raise forms.ValidationError(u"密码仅能用字母或数字")    
        return self.cleaned_data["password"]
        
    def clean(self):
        """验证其他非法"""
        cleaned_data = super(RegisterForm, self).clean()

        if cleaned_data.get("password") == cleaned_data.get("username"):
            raise forms.ValidationError(u"用户名和密码不能一样")
        if cleaned_data.get("password") != cleaned_data.get("re_password"):
            raise forms.ValidationError(u"两次输入密码不一致")

        return cleaned_data

    def save(self):
        username=self.cleaned_data["username"]
        email=self.cleaned_data["email"]
        password=self.cleaned_data["password"]
        user=User.objects.create_user(username,email,password)
        return user

accounts/views.py
from django.shortcuts import render

# Create your views here.

yunjz_prj/accounts/views.py
#coding=utf-8
#django package
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User  
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login ,logout as auth_logout
from django.core.urlresolvers import reverse

#myApp package
from accounts.forms import  RegisterForm
from jizhang.data_format_func import auto_gen_categories


def register(request):
    '''注册视图'''
    template_var={}
    form = RegisterForm()    
    if request.method=="POST":
        form=RegisterForm(request.POST.copy())
        if form.is_valid():
            form.save()
            if _login(request,form.cleaned_data['username'],form.cleaned_data['password'],template_var):
                auto_gen_categories(request.user.id)
                return HttpResponseRedirect(reverse("jizhang:items"))

    template_var["form"]=form 
             
    return render(request,"accounts/register.html",template_var)

	
def login(request):
    '''登陆视图'''
    template_var={}
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        if _login(request,username,password,template_var):
            try:
                tmp = request.GET['next']
                return HttpResponseRedirect(tmp)
            except:
                return HttpResponseRedirect(reverse("jizhang:items"))
 
        template_var.update({"username":username}) 
    return render(request,"accounts/login.html",template_var)


def _login(request,username,password,dict_var):
    '''登陆核心方法'''
    ret=False
    user=authenticate(username=username,password=password)
    if user is not None:
        if user.is_active:
            auth_login(request,user)
            ret=True
        else:
            dict_var["error"] = u'用户'+username+u'没有激活'
    else:
        dict_var["error"] = u'用户'+username+u'不存在或密码错误'  
    return ret


def logout(request):
    auth_logout(request)
    return render(request,'accounts/logout.html',)	
	

templates/accounts/index.html
{% extends "base_yunjz.html" %}
{%block title%}已退出{%endblock%}

{% block content %}
{% include "welcome.html"%}
{%endblock%}


templates/accounts/login.html
{% extends "base_yunjz.html" %}
{%block title%}登录{%endblock%}s
{% block content %}
        <h2 class="text-center"> 欢迎来到黑板客记账站点 </h2>
        {%if error%}
	    <p>{{error}}</p>
        {%endif%}

        <form action="" method="post" class="form"  role="form">
        {% csrf_token %}

            <div class="form-group">
                <label>昵称:</label> 
                <input class="form-control" id="id_username" name="username" type="text" value="{{username}}"/>
            </div>
            
            <div class="form-group">
                <label>密码:</label> 
                <input class="form-control" id="id_password" name="password" type="password" />
            </div>

        <button id='id_submit' type="submit" class="btn btn-default">登录</button>
        <button id='id_register' type='button' class="btn btn-default" onclick='javascrtpt:window.location.href="{% url 'accounts:register' %}"'>注册</button>
        </form>
        
        <h3> 在这里你可以</h3>
        <ul>
            <li>随时随地通过网络记账</li>
            <li>统计分析自己每月收支</li>
            <li>导出表格进行备份</li>
            <li>导入以前记录的表格</li>
        </ul>
{%endblock%}

templates/accounts/logout.html
{% extends "base_yunjz.html" %}
{%block title%}已退出{%endblock%}

{% block content %}
        <h2>感谢您的访问</h2>
        <h5>欢迎<a href="{% url 'accounts:login' %}">再次登录</a></h5> 
{%endblock%}


templates/accounts/register.html
{% extends "base_yunjz.html" %}
{%block title%}注册{%endblock%}

{% block content %}
  
    <h2 class="text-center"> 注册成为我们的一员吧 </h2>
    {%if form.non_field_errors%}
      {{form.non_field_errors}}
    {%endif%}
    <form action="" method="post" class="form"  role="form">
    {% csrf_token %}
        <div class="form-group">
            {{form.errors.username}}
            <label>昵称:</label> 
            <input class="form-control" id="id_username" name="username"  type="text" />
        </div>

        <div class="form-group">
        {{form.errors.email}}
            <label>邮件:</label> 
            <input class="form-control" id="id_email" name="email" type="email" />
        </div>
        
        <div class="form-group">
        {{form.errors.password}}
            <label>密码:</label> 
            <input class="form-control" id="id_password" name="password" type="password" />
        </div>
        

        <div class="form-group">
        {{form.errors.re_password}}
            <label>重复密码:</label> 
            <input class="form-control" id="id_re_password" name="re_password" type="password" />
        </div>
        
        <!--    
        {% for field in form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field.label_tag }} 
                {{ field }}
            </div>
        {% endfor %}
        -->
        
        <button type="submit" class="btn btn-default">注册</button>
        <button type='button' class="btn btn-default" onclick='javascrtpt:window.location.href="{% url 'accounts:login' %}"'>登录</button>
    </form>

{%endblock%}