accounts/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login',views.login,name='login'),
    url(r'^logout',views.logout, name='logout'),
    url(r'^register',views.register,name='register'),	
)

yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

yunjz_prj/yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/',include('jizhang.urls',namespace='jizhang')),
]

templates/base_yunjz.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN" >
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >

    <head>
        <title>{% block title %} 爱记账 {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'libs/pagination/pagination.css'%}" />
        <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css'%}"/>
        <link href="{% static 'libs/jquery-ui-1.11.2/jquery-ui.min.css'%}" rel="stylesheet" type="text/css"/>
        
        <script src="{% static 'libs/jquery.js'%}"></script>
        <!--[if lt IE 9]><script src="{% static 'libs/bootstrap/js/ie8-responsive-file-warning.js'%}"></script><![endif]-->


        <!--[if lt IE 9]>
          <script src="{% static 'libs/bootstrap/js/html5shiv.js'%}"></script>
          <script src="{% static 'libs/bootstrap/js/respond.min.js'%}"></script>
        <![endif]-->
        <script src="{% static 'libs/pagination/jquery.pagination.js'%}"></script>
        <script src="{% static 'libs/bootstrap/js/bootstrap.min.js'%}"></script>
        <script src="{% static 'libs/jquery-ui-1.11.2/jquery-ui.min.js'%}"></script>
        {%block extra_header%} {%endblock%}
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-1 col-md-2 col-lg-3"></div>
                    <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
                    {%block content%} {%endblock%}
                    {% include "footer.html" %}
                    </div>
                <div class="col-sm-1 col-md-2 col-lg-3"></div>
            </div>
        </div>
    </body>
</html>

templates/footer.html
<div class="text-center">
<a href="http://www.heibanke.com/jizhang/" target="_blank" >Demo is here</a> Powered By Django
</div>    

templates/welcome.html

<h5>欢迎 {{request.user}} 访问我们站点!   <a href="/accounts/logout/">注销</a></h5>

<!--
<h5>欢迎 {{ username}} 访问我们站点!   <a href="{% url 'accounts:logout' %}">注销</a></h5>

-->