jizhang/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin


from jizhang import views

admin.autodiscover()

urlpatterns = patterns('',
    # items
    url(r'^$', views.items, name="items"),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_item, name='edit_item'),
    url(r'^new/$',views.new_item,name='new_item'),
    url(r'^find/$',views.find_item,name='find_item'),
    #categorys
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^categories/(?P<pk>\d+)/$', views.show_category, name='show_category'),    
    url(r'^categories/(?P<pk>\d+)/edit/$', views.edit_category, name='edit_category'),
    url(r'^categories/new/$',views.new_category,name='new_category'), 
    #ajax
    url(r'^ajax/autocomplete_comments/',views.autocomplete_comments),
)

yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

yunjz_prj/jizhang/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin


from jizhang import views

admin.autodiscover()

urlpatterns = patterns('',
    # items
    url(r'^$', views.items, name="items"),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_item, name='edit_item'),
    url(r'^new/$',views.new_item,name='new_item'),
    url(r'^find/$',views.find_item,name='find_item'),
    #categorys
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^categories/(?P<pk>\d+)/$', views.show_category, name='show_category'),    
    url(r'^categories/(?P<pk>\d+)/edit/$', views.edit_category, name='edit_category'),
    url(r'^categories/new/$',views.new_category,name='new_category'), 
    #ajax
    url(r'^ajax/autocomplete_comments/',views.autocomplete_comments),
)

yunjz_prj/yunjz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^jizhang/',include('jizhang.urls',namespace='jizhang')),
]

jizhang/models.py
from django.db import models

# Create your models here.

yunjz_prj/jizhang/models.py
#coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class Category(models.Model):
    INCOME_CHOICES = (
        (True, u'收入'),
        (False, u'支出'),
    )
    p_category = models.ForeignKey('self', null = True, blank = True, verbose_name=u"父类名称", related_name='childs')
    name = models.CharField(max_length=20, verbose_name=u"类别名称")
    isIncome = models.BooleanField(choices=INCOME_CHOICES, verbose_name=u'是否收入')
    user = models.ForeignKey(User,verbose_name=u'所属用户')

    def __unicode__(self):
        return self.level()+self.name

    def get_absolute_url(self):
        return '%s' % (reverse('jizhang:edit_category', args=(self.id,))) 

    def get_items_url(self):
        return '%s' % (reverse('jizhang:show_category', args=(self.id,))) 
    
    #shiyan7
    def level(self):
        if self.p_category:
            return "----"+self.p_category.level()
        else:
            return ""
    
    #shiyan7
    def save(self, *args, **kwargs):
        #form保证了子类不能修改isIncome，只能修改顶级父类的isIncome
        #遍历一遍childs，统一设置isIncome
        for child in self.childs.all():
            if child.isIncome != self.isIncome:
                child.isIncome = self.isIncome
                child.save()
                
        super(self.__class__, self).save(*args, **kwargs)        

class Item(models.Model):
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name=u'金额')
    comment = models.CharField(max_length=200, blank = True, verbose_name=u'注释')
    pub_date = models.DateField(verbose_name=u'日期')
    category = models.ForeignKey(Category,verbose_name=u'分类', related_name='items')  
    
    class Meta:
        ordering = ["-pub_date"]
        
    def __unicode__(self):
        return str(self.price)

    def get_absolute_url(self):
        return '%s' % (reverse('jizhang:edit_item', args=(self.id,))) 
    
    def get_price(self):
        if self.category.isIncome:
            return self.price
        else:
            return -1*self.price

    def save(self, *args, **kwargs):
        if self.price<0:
            self.price = -1*self.price
        super(self.__class__, self).save(*args, **kwargs)

jizhang/forms.py
#coding=utf-8
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget

# Register your models here.
from jizhang.models import Item, Category
from jizhang.data_format_func import get_sorted_categories
		
class CategoryForm(ModelForm):

    class Meta:
        model = Category
        fields = ('name', 'p_category', 'isIncome')


    def __init__(self, request, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.user = request.user
        
        categories=get_sorted_categories(self.user.username)
        
        self.fields['p_category'].widget = forms.Select(attrs={'class':"form-control"})
        self.fields['p_category'].choices = [('',u'----------------')] + [(c.id,c) for c in categories]

        self.fields['name'].widget = forms.TextInput(attrs={'class':"form-control"})
        self.fields['isIncome'].widget = forms.CheckboxInput(attrs={'checkbox':True})

    def clean_isIncome(self):
        if self.cleaned_data['p_category']:
            if not self.cleaned_data['p_category'].isIncome==self.cleaned_data['isIncome']:
                raise forms.ValidationError(u"是否收入应和父类别一致.")	
        return self.cleaned_data['isIncome']

    def save(self,id=None):
        new_category = Category(name=self.cleaned_data['name'],
        p_category=self.cleaned_data['p_category'],
        user = self.user,
        isIncome=self.cleaned_data['isIncome'],
        id = id)
        new_category.save()

class NewCategoryForm(CategoryForm):

	# new category name must not repeat
    def clean_name(self):
        try:
            # user = request.user
            repeat_category = Category.objects.filter(user__username=self.user.username).get(name=self.cleaned_data['name'])
        except Category.DoesNotExist:
            return self.cleaned_data['name']
        raise forms.ValidationError(u"该名称类别已有，请使用其他的名称.")	


class ItemForm(ModelForm):

    class Meta:
        model = Item
        fields = ('pub_date', 'category', 'price', 'comment')

    def save(self, id=None):
        new_item = Item(category=self.cleaned_data['category'],
            price=self.cleaned_data['price'],
            pub_date=self.cleaned_data['pub_date'],
            comment=self.cleaned_data['comment'],
            id = id)            
        new_item.save()
        
    def __init__(self, request, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        
        categories=get_sorted_categories(request.user.username)
        
        self.fields['category'].widget = forms.Select(attrs={'class':"form-control"})
        self.fields['category'].choices = [(c.id,c) for c in categories]
        
        self.fields['pub_date'].widget = forms.DateInput(attrs={'class':"datepicker form-control"})
        self.fields['price'].widget = forms.TextInput(attrs={'class':"form-control"})
        self.fields['comment'].widget = forms.TextInput(attrs={'class':"form-control"})


class FindItemForm(forms.Form):	
	start_date = forms.DateField(label=u'开始时间',required=False, widget=forms.DateInput(attrs={'size': 20,'class':"datepicker form-control"}))
	end_date = forms.DateField(label=u'结束时间',widget=forms.DateInput(attrs={'size': 20,'class':"datepicker form-control"}))
	category = forms.ChoiceField(label=u'选择分类',required=False)
	query = forms.CharField(label=u'备注关键字',required=False,widget=forms.TextInput(attrs={'class':"form-control"}))	
	
	def __init__(self, request, *args, **kwargs):
		super(FindItemForm, self).__init__(*args, **kwargs)
		categories=get_sorted_categories(request.user.username)
					
		self.fields['category'].widget = forms.Select(attrs={'class':"form-control"})
		self.fields['category'].choices = [('',u'所有分类')] + [(c.id,c) for c in categories]	

	def clean_query(self):
		if not self.cleaned_data['start_date']:
			if not self.cleaned_data['query']:
				raise forms.ValidationError(u"开始时间和关键字至少要有一个.")
		return self.cleaned_data['query']
        
	def clean_end_date(self):
		if not self.cleaned_data['start_date']:
			return self.cleaned_data['end_date']
		else:
			if self.cleaned_data['end_date'] > self.cleaned_data['start_date']:
				return self.cleaned_data['end_date']
			else:
				raise forms.ValidationError(u"结束时间需要晚于开始时间.")	

jizhang/views.py
#coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseRedirect,HttpResponse
from django.db.models import Sum, Count, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv, json

#myApp package
from jizhang.models import Item, Category
from jizhang.forms import ItemForm, CategoryForm, NewCategoryForm, FindItemForm
from jizhang.data_format_func import get_sorted_categories

# shiyan9
# ajax  --done, views.py, new_item.html, jslib
# register auto gen  --done, accounts/views.py,tests.py, jizhang/data_format_func,
# datepicker --done, new_item.html, find_item.html
# find pages --done, views.py, find_item_results.html

PAGE_ITEM_NUM = 5
    
def split_page(request, data, page_item_num):
    side_show_page_num = 2
    
    p = Paginator(data , page_item_num)
    page = request.GET.get('page') # Get page
    try:
        item_page = p.page(page)
    except PageNotAnInteger:
        item_page = p.page(1)
    except EmptyPage:
        item_page = p.page(p.num_pages)     
    
    page_list = [-1]*len(p.page_range)
    
    for i in p.page_range:
        if i==1 or i==p.num_pages or (i<=item_page.number+side_show_page_num and i>=item_page.number-side_show_page_num):
            page_list[i-1]=i
        elif i==item_page.number+side_show_page_num+1 or i==item_page.number-side_show_page_num-1:
            page_list[i-1]=0
    
    return item_page, page_list  


def delete_items(cls,ids):
    for item_id in ids:
        del_item = get_object_or_404(cls, id=item_id)
        del_item.delete()


# Create your views here.
@login_required
def categories(request, template_name='jizhang/categories.html'):
    if request.method == 'POST':
        ## delete categories
        del_ids = request.POST.getlist('del_id')
        delete_items(Category,del_ids)
                
    return render(request, template_name, {"categories":get_sorted_categories(request.user.username)})

@login_required
def show_category(request, pk, template_name='jizhang/items.html'):
    if request.method == 'POST':
        ## delete items
        del_ids = request.POST.getlist('del_id')
        delete_items(Item,del_ids)
            
    item_list = Item.objects.filter(category__user__username=request.user.username).filter(category__id=pk)
    item_page,page_num_list = split_page(request, item_list, PAGE_ITEM_NUM)
    
    return render(request, template_name, {'items':item_page,'page_num_list':page_num_list})

@login_required    
def edit_category(request,pk, template_name='jizhang/new_category.html'):
    out_errors = []
    if request.method == 'POST':
        form = CategoryForm(request,data=request.POST)
        if form.is_valid():
            form.save(pk)
            return HttpResponseRedirect("/jizhang/categories")
    else:
        category_list = get_object_or_404(Category, id=pk) 
        form = CategoryForm(request,instance=category_list)
    return render(request, template_name,{'form':form})

@login_required
def new_category(request, template_name='jizhang/new_category.html'):
    if request.method == 'POST':
        form = NewCategoryForm(request,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/jizhang/categories")
    else:
        form = NewCategoryForm(request)
    return render(request, template_name, {'form':form})


@login_required
def items(request, template_name='jizhang/items.html'):
    if request.method == 'POST':
        ## delete items
        del_ids = request.POST.getlist('del_id')
        delete_items(Item,del_ids)

    item_list = Item.objects.filter(category__user__username=request.user.username)
    item_page,page_num_list = split_page(request, item_list, PAGE_ITEM_NUM)

    return render(request, template_name, {'items':item_page,'page_num_list':page_num_list})


@login_required 
def edit_item(request, pk, template_name='jizhang/new_item.html'):
    if request.method == 'POST':

        form = ItemForm(request,data=request.POST)
        if form.is_valid():
            form.save(pk)
            return HttpResponseRedirect("/jizhang")
    else:
        item_list = get_object_or_404(Item, id=pk)
        form = ItemForm(request,instance=item_list)

    return render(request, template_name,{'form':form})


@login_required 
def new_item(request, template_name='jizhang/new_item.html'):
    if request.method == 'POST':
        form = ItemForm(request,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/jizhang")
    else:
        form = ItemForm(request,initial={'pub_date':timezone.now().date()})

    return render(request, template_name,{'form':form})


def config_qset(query):
    qset = (
            Q(comment__icontains=query)
        )
    return qset

def config_category_qset(id):
    qset = ()
    ff = get_object_or_404(Category, id=id)
    qset = (Q(category__id=ff.id))
    
    for child in ff.childs.all():
        qset = qset | config_category_qset(child.id)

    return qset
    
@login_required 
def find_item(request):
    if request.method == 'POST':
        del_ids = request.POST.getlist('del_id')
        
        if del_ids:
            for item_id in del_ids:
                del_item = get_object_or_404(Item, id=item_id)
                del_item.delete()
            return HttpResponseRedirect("/jizhang")
                
        else:    

            form = FindItemForm(request,data=request.POST)
            if form.is_valid():
                # time search
                if not form.cleaned_data['start_date']:
                    item_list = Item.objects.filter(category__user__username=request.user.username).all()
                else:
                    item_list = Item.objects.filter(category__user__username=request.user.username).filter(pub_date__range=(form.cleaned_data['start_date'],form.cleaned_data['end_date']))

                # category search
                category_id = form.cleaned_data['category']
                if not category_id:
                    item_category = item_list
                else:
                    category_qset=config_category_qset(category_id)
                    item_category = item_list.filter(category_qset).distinct()

                # key words search
                query = form.cleaned_data['query']
                if not query:   
                    results = item_category
                else:                
                    query_list = query.strip().split(' ')
                    qset =()
                    for every_query in query_list:
                        if not qset:
                            qset = config_qset(every_query)
                        else:
                            qset = qset|config_qset(every_query)

                    results = item_category.filter(qset).distinct()
                    
                p = Paginator(results , PAGE_ITEM_NUM)
                item_pages = []
                for i in p.page_range:
                    item_pages.append(p.page(i))
                    
                return render(request,'jizhang/find_item_results.html', {'item_pages': item_pages})
    else:
        form = FindItemForm(request,initial={'start_date':None,'end_date':timezone.now().date()})
    return render(request,'jizhang/find_item.html',{'form':form})
    
    

@login_required    
def autocomplete_comments(request):
    term = request.GET.get('term')

    if not term:
        items=Item.objects.filter(category__user__username=request.user.username)[:12]
    else:
        items=Item.objects.filter(category__user__username=request.user.username).filter(comment__icontains=term)[:12]
    
    print (items)
    json_send = []
    have_track = []
    for item in items:
        if [item.comment,item.category.id] not in have_track:
            have_track.append([item.comment,item.category.id])
            json_send.append({"id": item.id,
                             "category_id": item.category.id,
                             "label": item.comment+"--"+item.category.name,
                             "value": item.comment
                             })
                             
    print (have_track,json_send)
    return HttpResponse(json.dumps(json_send), content_type="application/json") 

templates/jizhang/categories.html
{% extends "base_yunjz.html" %}
{%block title%}分类列表{%endblock%}

{%block extra_header%}
<script>
    $(function () {
        $("#all").click(function () {
            var checked_status = this.checked;
            $("input[name=del_id]").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>
{% endblock%}
        
{% block content %}

{% include "welcome.html" %}

    <div class="btn-group btn-group-justified" role="group">
        <a href="{% url 'jizhang:new_category' %}"  class="btn btn-primary" role="button"><span class="glyphicon glyphicon-plus"></span> 新建</a>
        <a href="#" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-save"></span> 导出</a>
        <a href="#" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-open"></span> 导入</a>
        <a data-toggle="modal" data-target="#myModal"  class="btn btn-danger" role="button"><span class="glyphicon glyphicon-trash"></span> 删除</a>
    </div>

    <form method="post" action="" name="itemsForm">
        {% csrf_token %}

        <table class="table table-striped">
            {% if categories %}
                <tr class="info"><td><strong>分类名称</strong></td>
                    <td><strong>父类名称</strong></td>
                    <td><strong>收入/支出</strong></td>
                    <td><strong><input type="checkbox" id="all" />全选</strong></td>
                </tr>

                {% for obj in categories %}
                    <tr class="{% cycle ,active %}">
                        <td data-toggle="tooltip" data-placement="left" title="编辑该分类"><a href="{% url 'jizhang:edit_category' obj.id %}" >{{obj.level}}{{ obj.name}}</a></td>
                        <td>{{ obj.p_category}}</td>
                        <td> {{ obj.get_isIncome_display}} </td>
                        <td><input type='checkbox' name="del_id" value="{{obj.id}}"></td>
                    </tr>
                {% endfor %}
            {% else %}
                <p>没有可用的分类</p>
            {% endif %}

        </table>

        {%include "jizhang/delete_modal.html"%}
    </form>

    {% include "jizhang/footer_button.html" %}

{%endblock%}

templates/jizhang/find_item.html
{% extends "base_yunjz.html" %}
{%block title%}查找收支{%endblock%}


{%block extra_header%}
<script>  
$(function(){
    $( ".datepicker" ).datepicker({dateFormat: 'yy-mm-dd'});
});
</script>
{%endblock%}


{% block content %}

{% include "welcome.html" %}

<form method="post" action=""  role="form" >
{% csrf_token %}

{% if form.non_fields_error %}
<ul class="errorlist"><li>{{form.non_fields_error}}</li>
{% endif %}



{% for field in form %}

    {% if field.field.widget.attrs.checkbox %}
        <div class="checkbox">
        {{ field.errors }}
        
        {{ field }}{{ field.label }} 
        </div>

    {% else %}
        <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }} 
        {{ field }}
        </div>
    {% endif %}

{% endfor %}


<p></p>
<p></p>
<button type="submit" class="btn btn-primary" name="return_list"><span class="glyphicon glyphicon-ok"></span> 提交</button>
<a type='button'  href="{% url 'jizhang:items'%}" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-left"></span> 返回</a>

</form>


{%endblock%}

templates/jizhang/find_item_results.html

{% extends "base_yunjz.html" %}
{%block title%}查找结果{%endblock%}
{%block extra_header%}

    <script type="text/javascript">

    $(function(){

        $("#all").click(function () {
            var checked_status = this.checked;
            $("input[name=del_id]").each(function () {
                this.checked = checked_status;
            });
        });

        //这是一个非常简单的demo实例，让列表元素分页显示
        //回调函数的作用是显示对应分页的列表项内容
        //回调函数在用户每次点击分页链接的时候执行
        //参数page_index{int整型}表示当前的索引页
        var initPagination = function() {
            var num_entries = $("#hiddenresult div.result").length;
            // 创建分页
            $("#Pagination").pagination(num_entries, {
                num_edge_entries: 1, //边缘页数
                num_display_entries: 4, //主体页数
                callback: pageselectCallback,
                prev_text: "前一页",
                next_text: "下一页",
                items_per_page:1 //每页显示1项
            });
         }();
         
        function pageselectCallback(page_index, jq){
            var new_content = $("#hiddenresult div.result:eq("+page_index+")").clone();
            $("#Searchresult").empty().append(new_content); //装载对应分页的内容
            return false;
        };
    });
    </script>
{% endblock%}
        
{% block content %}

    {% include "welcome.html" %}

    <div class="btn-group btn-group-justified" role="group">
        <a href="{% url 'jizhang:new_item' %}"           class="btn btn-primary" role="button"><span class="glyphicon glyphicon-plus"></span> 新建</a>
        <a href="#" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-save"></span> 导出</a>
        <a href="#"    class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-open"></span> 导入</a>
        <!-- Button trigger modal -->
        <a data-toggle="modal" data-target="#myModal"  class="btn btn-danger"  role="button"><span class="glyphicon glyphicon-trash"></span> 删除</a>           

    </div>

    <form method="post" action="" name="itemsForm">
    {% csrf_token %}

    <div id="Searchresult">正在加载。。。</div>  
    <div id="Pagination" class="pagination"><!-- 这里显示分页 --></div>        
    <div id="hiddenresult" style="display:none;">
        {%for items in item_pages%}
            {{items}}
            <div class="result">
                <table class="table table-striped">
                    {% if items %}
                        <tr class="info"><td data-toggle="tooltip" data-placement="left" title="按时间排序"><strong><a href="{%url 'jizhang:items'%}">时间</a></strong></td>
                            <td data-toggle="tooltip" data-placement="left" title="按价格排序">价格(元)</td>
                            <td><strong>分类</strong></td>
                            <td><strong>备注</strong></td>
                            <td><strong><input type="checkbox" id="all" />全选</strong></td>
                        </tr>

                    
                        {% for item in items %}
                        <tr class="{% cycle ,active %}">
                            <td data-toggle="tooltip" data-placement="left" title="编辑该帐单"><a href="{{item.get_absolute_url}}">{{ item.pub_date|date:"Y-m-d"}}</a></td>
                            <td data-toggle="tooltip" data-placement="left" title="编辑该帐单"><a href="{{item.get_absolute_url}}">{{ item.get_price}}</a></td>
                            <td data-toggle="tooltip" data-placement="left" title="显示该分类下帐单"><a href="{{item.category.get_items_url}}"> {{ item.category}}</a> </td>
                            <td> {{ item.comment}} </td>
                            <td><input type='checkbox' name="del_id" value="{{item.id}}"></td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <p>没有可用的帐单</p>
                    {% endif %}

                </table>
            </div>
        {%endfor%}
    </div>

    {%include "jizhang/delete_modal.html"%}
    </form>

    {% include "jizhang/footer_button.html" %}

{%endblock%}




templates/jizhang/footer_button.html
<div class="btn-group btn-group-justified" role="group">
    <a type='button' class="btn btn-primary"  href="{% url 'jizhang:items' %}"><span class="glyphicon glyphicon-list"></span> 帐单</a>
    <a type='button' class="btn btn-primary"  href="{% url 'jizhang:categories' %}"><span class="glyphicon glyphicon-briefcase"></span> 分类</a>
    <a type='button' class="btn btn-primary"  href="{% url 'jizhang:find_item' %}"><span class="glyphicon glyphicon-search"></span> 查找</a>
    <a type='button' class="btn btn-primary"  href="#"><span class="glyphicon glyphicon-stats"></span> 报告</a>
</div>

templates/jizhang/items.html

{% extends "base_yunjz.html" %}
{%block title%}收支列表{%endblock%}

{%block extra_header%}
<script>
    $(function () {
        $("#all").click(function () {
            var checked_status = this.checked;
            $("input[name=del_id]").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>
{% endblock%}


{% block content %}

{% include "welcome.html" %}

        <div class="btn-group btn-group-justified" role="group">
            <a href="{% url 'jizhang:new_item' %}"           class="btn btn-primary" role="button"><span class="glyphicon glyphicon-plus"></span> 新建</a>
            <a href="#" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-save"></span> 导出</a>
            <a href="#"    class="btn btn-primary" role="button"><span class="glyphicon glyphicon-floppy-open"></span> 导入</a>
            <!-- Button trigger modal -->
            <a data-toggle="modal" data-target="#myModal" class="btn btn-danger"  role="button"><span class="glyphicon glyphicon-trash"></span> 删除</a>           

        </div>

        <form method="post" action="" name="itemsForm">
        {% csrf_token %}

            <table class="table table-striped">
                {% if items %}
                    <tr class="info"><td data-toggle="tooltip" data-placement="left" title="按时间排序"><strong><a href="{%url 'jizhang:items'%}">时间</a></strong></td>
                        <td data-toggle="tooltip" data-placement="left" title="按价格排序">价格(元)</td>
                        <td><strong>分类</strong></td>
                        <td><strong>备注</strong></td>
                        <td><strong><input type="checkbox" id="all" />全选</strong></td>
                    </tr>

                
                    {% for item in items %}
                    <tr class="{% cycle ,active %}">
                        <td data-toggle="tooltip" data-placement="left" title="编辑该帐单"><a href="{{item.get_absolute_url}}">{{ item.pub_date|date:"Y-m-d"}}</a></td>
                        <td data-toggle="tooltip" data-placement="left" title="编辑该帐单"><a href="{{item.get_absolute_url}}">{{ item.get_price}}</a></td>
                        <td data-toggle="tooltip" data-placement="left" title="显示该分类下帐单"><a href="{{item.category.get_items_url}}"> {{ item.category}}</a> </td>
                        <td> {{ item.comment}} </td>
                        <td><input type='checkbox' name="del_id" value="{{item.id}}"></td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <p>没有可用的帐单</p>
                {% endif %}

            </table>
            <ul class="pagination">
                {% if items.has_previous %}
                   <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
                {% else%}
                   <li class="disable"><a>&laquo;</a></li>
                {% endif %}
                
                {% for i in page_num_list %} 
                    {%if i > 0%}
                    <li {%ifequal items.number forloop.counter%}class="active"{%endifequal%}><a href="?page={{ i }}">{{i}}</a></li>
                    {%elif i == 0%}
                    <li><a><strong>...</strong></a></li>
                    {%endif%}
                {% endfor %}
                {% if items.has_next %}
                   <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
                {% else %}
                   <li class="disable"><a>&raquo;</a></li>
                {% endif %}
            </ul>


            {%include "jizhang/delete_modal.html"%}

        </form>

        {% include "jizhang/footer_button.html" %}

{%endblock%}




templates/jizhang/new_item.html
{% extends "base_yunjz.html" %}
{%block title%}新建/编辑收支{%endblock%}


{%block extra_header%}
<script>  


$(function(){
    $( ".datepicker" ).datepicker({dateFormat: 'yy-mm-dd'});
});

$(function(){ 
    $( "#id_comment" ).autocomplete({
      source: "/jizhang/ajax/autocomplete_comments",
      minLength: 2,
      select: function( event, ui ) {
        $("#id_category").val(ui.item.category_id);
      }
    });
});   
</script>
{%endblock%}


{% block content %}

{% include "welcome.html" %}

<form method="post" action=""  role="form" >
{% csrf_token %}

{% if form.non_fields_error %}
<ul class="errorlist"><li>{{form.non_fields_error}}</li>
{% endif %}



{% for field in form %}

    {% if field.field.widget.attrs.checkbox %}
        <div class="checkbox">
        {{ field.errors }}
        
        {{ field }}{{ field.label }} 
        </div>

    {% else %}
        <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }} 
        {{ field }}
        </div>
    {% endif %}

{% endfor %}


<p></p>
<p></p>
<button type="submit" class="btn btn-primary" name="return_list"><span class="glyphicon glyphicon-ok"></span> 提交</button>
<a type='button'  href="{% url 'jizhang:items'%}" class="btn btn-primary"><span class="glyphicon glyphicon-arrow-left"></span> 返回</a>

</form>


{%endblock%}